# PVC for scan data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-antivirus-scan-pvc
  namespace: justice-gov-uk-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: s3-antivirus-scan-job
  namespace: justice-gov-uk-dev
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: justice-gov-uk-dev-av
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        seccompProfile:
          type: "RuntimeDefault"
      containers:
      - name: s3-antivirus-scan
        image: ghcr.io/ministryofjustice/s3-antivirus-scan:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: CLAMAV_PORT
            value: "3310"
          - name: CLAMAV_MAX_FILE_SIZE
            value: "250000000"  # 250MB in bytes
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: s3-bucket-output
                key: bucket_name
          - name: S3_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: s3-bucket-output
                key: bucket_domain_name
          - name: S3_ENDPOINT
            value: https://s3.eu-west-2.amazonaws.com
          - name: S3_REGION
            value: eu-west-2
        volumeMounts:
          - name: scan-data
            mountPath: /data
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: 
            drop: ["ALL"]
      volumes:
        - name: scan-data
          persistentVolumeClaim:
            claimName: s3-antivirus-scan-pvc
      restartPolicy: Never
---
