name: Test and deploy to Github Container Registry

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  deploy:
    name: Build and Deploy
    needs: test
    uses: ./.github/workflows/deploy.yml
